baseurl: /site
exclude: [README.md]
permalink: pretty
name: Paragaze
description: "New Writings on Art and Culture"
url: https://paragaze.github.io
logo: /assets/img/logo1.png
locale: en_CA
author:
  facebook: davidbroadfoot
  twitter: davidbroadfoot
