exclude: [README.md]
permalink: pretty
name: Paragaze
title: Paragaze
description: "New Writings on Art and Culture"
url: paragaze.ca
logo: /assets/img/logo1.png
locale: en_CA
author:
  facebook: davidbroadfoot
  twitter: davidbroadfoot
